name: snapclean
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.14.0
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  custom_radio_grouped_button: ^2.2.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  freezed_annotation: ^2.4.1
  geolocator: ^10.1.0
  get: 4.6.6
  getwidget: ^4.0.0
  google_maps_flutter: ^2.5.2
  image_picker: ^1.0.7
  intl: ^0.18.0
  json_annotation: ^4.8.1
  syncfusion_flutter_charts: ^24.1.44+1

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appIcon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/appIcon.jpg"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/appIcon.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/appIcon.jpg"
