name: snapclean
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.14.0
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  custom_radio_grouped_button: ^2.2.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  get: 4.6.6
  google_maps_flutter: ^2.5.2
  image_picker: ^1.0.7
  intl: ^0.18.0
  syncfusion_flutter_charts: ^24.1.44+1
  getwidget: ^4.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
